#!/usr/bin/env python3
"""
Build the embedded webfont subset used by the receipt / invoice document
in LayerTrack.html and BroodTrack.html.

Why embed at all: the receipt is the only artifact that leaves the farm, it
gets printed to PDF and screenshotted, and a font fallback is most visible
exactly there. Embedding also means it renders identically offline.

Three faces only, two weights of Archivo plus one of IBM Plex Mono. Bold mono
was dropped deliberately -- the stub gets its emphasis from size and colour,
which saved ~18 KB.

Charset is plain alphabet plus the handful of symbols the document uses (naira,
multiply, middot, dashes). Extended African Latin letters were measured at
+30 KB and dropped as unnecessary; a name carrying an accent still renders, it
just falls back to the device font for that one glyph.

Requires: pip install fonttools brotli
Usage:    python build_receipt_fonts.py
Writes:   receipt-src/fonts.css
"""

import base64
import logging
import os
import shutil
import sys
import tempfile
import urllib.request

logging.getLogger("fontTools").setLevel(logging.ERROR)

try:
    from fontTools import ttLib
    from fontTools.subset import Options, Subsetter
    from fontTools.varLib import instancer
except ImportError:
    sys.exit("Missing dependency. Run: pip install fonttools brotli")

GF = "https://github.com/google/fonts/raw/main/ofl"
SOURCES = {
    "archivo-var.ttf": f"{GF}/archivo/Archivo%5Bwdth,wght%5D.ttf",
    "plex-regular.ttf": f"{GF}/ibmplexmono/IBMPlexMono-Regular.ttf",
}

# (source, css family, css weight, variable-font wght instance or None)
FACES = [
    ("archivo-var.ttf", "ReceiptSans", 400, 400),
    ("archivo-var.ttf", "ReceiptSans", 800, 800),
    ("plex-regular.ttf", "ReceiptMono", 400, None),
]

OUT = os.path.join("receipt-src", "fonts.css")


def charset():
    """Plain alphabet only, per the farm owner's call -- extended African Latin
    letters were dropped to keep the payload small. A name containing an accent
    still renders, it just falls back to the device font for that one glyph."""
    cp = []
    cp += range(0x20, 0x7F)                       # ASCII printable
    cp += [0xA0, 0xB7, 0xD7]                      # nbsp, middot separator, multiply
    cp += [0x2013, 0x2014]                        # en dash, em dash ("Eggs — Crates")
    cp += [0x2018, 0x2019, 0x201C, 0x201D, 0x2026]  # smart quotes, ellipsis
    cp += [0x20A6]                                # naira
    return sorted(set(cp))


def fetch(tmp):
    for name, url in SOURCES.items():
        dest = os.path.join(tmp, name)
        print(f"  fetching {name}")
        with urllib.request.urlopen(url) as r, open(dest, "wb") as f:
            shutil.copyfileobj(r, f)


def build_face(tmp, src, wght, chars):
    font = ttLib.TTFont(os.path.join(tmp, src))
    if wght is not None:
        font = instancer.instantiateVariableFont(font, {"wght": wght, "wdth": 100})
    opts = Options()
    opts.flavor = "woff2"
    opts.desubroutinize = True
    # tnum matters: every figure on the document is set with tabular-nums so
    # columns of naira amounts line up.
    opts.layout_features = ["kern", "tnum", "ccmp", "mark", "mkmk", "locl"]
    opts.name_IDs = []
    opts.name_legacy = False
    sub = Subsetter(options=opts)
    sub.populate(unicodes=chars)
    sub.subset(font)
    out = os.path.join(tmp, f"sub-{src}-{wght}.woff2")
    font.flavor = "woff2"
    font.save(out)
    return open(out, "rb").read()


def main():
    chars = charset()
    print(f"charset: {len(chars)} codepoints")
    blocks = []
    total = 0
    with tempfile.TemporaryDirectory() as tmp:
        fetch(tmp)
        for src, family, weight, inst in FACES:
            raw = build_face(tmp, src, inst, chars)
            b64 = base64.b64encode(raw).decode("ascii")
            total += len(b64)
            print(f"  {family} {weight:3d}  {len(raw)/1024:5.1f} KB -> {len(b64)/1024:5.1f} KB base64")
            blocks.append(
                "@font-face{"
                f"font-family:'{family}';font-style:normal;font-weight:{weight};"
                "font-display:swap;"
                f"src:url(data:font/woff2;base64,{b64}) format('woff2')"
                "}"
            )

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    header = (
        "/* GENERATED by build_receipt_fonts.py -- do not hand-edit.\n"
        "   Subset webfonts for the receipt/invoice document.\n"
        f"   {len(chars)} codepoints, {len(FACES)} faces, ~{total/1024:.0f} KB base64 total.\n"
        "   Archivo and IBM Plex Mono, both SIL Open Font License 1.1. */\n"
    )
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(header + "\n".join(blocks) + "\n")
    print(f"\nwrote {OUT}  ({os.path.getsize(OUT)/1024:.1f} KB)")


if __name__ == "__main__":
    main()
